In [2]:
import numpy as np
import pandas as pd
import ast
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem.porter import PorterStemmer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
jobs = pd.read_csv('job_title_des.csv')

In [23]:
jobs

Unnamed: 0              Job Title  \
0              0      Flutter Developer   
1              1       Django Developer   
2              2       Machine Learning   
3              3          iOS Developer   
4              4   Full Stack Developer   
...          ...                    ...   
2272        2399      Backend Developer   
2273        2400   Full Stack Developer   
2274        2401  Network Administrator   
2275        2402       Machine Learning   
2276        2403   Full Stack Developer   

                                        Job Description  \
0     We are looking for hire experts flutter develo...   
1     PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...   
2     Data Scientist (Contractor)\n\nBangalore, IN\n...   
3     JOB DESCRIPTION:\n\nStrong framework outside o...   
4     job responsibility full stack engineer – react...   
...                                                 ...   
2272  Job Summary\nPublished on : 26 days ago\nVacan...   
2273  business entity cisco umbrella focus cloud-bas...   
2274  Urgently reqd in a college in Mohali\nNetwork ...   
2275  Key Responsibilities: Team leads for small or ...   
2276  leslie hindman auctioneer one nation 's leadin...   

                       Jobs                                               tags  
0         Flutter Developer  we are looking for hire experts flutter develo...  
1          Django Developer  python/django (developer/lead) - job code(pdj ...  
2          Machine Learning  data scientist (contractor)\n\nbangalore, in\n...  
3             iOS Developer  job description:\n\nstrong framework outside o...  
4      Full Stack Developer  job responsibility full stack engineer – react...  
...                     ...                                                ...  
2272      Backend Developer  job summary\npublished on : 26 days ago\nvacan...  
2273   Full Stack Developer  business entity cisco umbrella focus cloud-bas...  
2274  Network Administrator  urgently reqd in a college in mohali\nnetwork ...  
2275       Machine Learning  key responsibilities: team leads for small or ...  
2276   Full Stack Developer  leslie hindman auctioneer one nation 's leadin...  

[2277 rows x 5 columns]

In [9]:
jobs['Jobs'] = jobs['Job Title'] 

In [7]:
jobs.isnull().sum()

Unnamed: 0         0
Job Title          0
Job Description    0
dtype: int64

In [8]:
jobs.duplicated().sum()

0

In [10]:
jobs['tags'] = jobs['Job Description'] + " " + jobs['Job Title']
jobs['tags'] = jobs['tags'].apply(lambda x:x.lower())

In [11]:
jobs['tags'][0]

'we are looking for hire experts flutter developer. so you are eligible this post then apply your resume.\njob types: full-time, part-time\nsalary: ₹20,000.00 - ₹40,000.00 per month\nbenefits:\nflexible schedule\nfood allowance\nschedule:\nday shift\nsupplemental pay:\njoining bonus\novertime pay\nexperience:\ntotal work: 1 year (preferred)\nhousing rent subsidy:\nyes\nindustry:\nsoftware development\nwork remotely:\ntemporarily due to covid-19 flutter developer'

In [12]:
cv = CountVectorizer(max_features=100, stop_words='english')
vectors = cv.fit_transform(jobs['tags']).toarray()
vector = cv.fit_transform(["javascript html cs  react.js node.js angular.js mongodb aws java developed user interface with modern javascript frame"]).toarray()

In [13]:
vector

array([[1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1]], dtype=int64)

In [14]:
cv.get_feature_names()

C:\Users\shiva\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['angular',
 'aws',
 'cs',
 'developed',
 'frame',
 'html',
 'interface',
 'java',
 'javascript',
 'js',
 'modern',
 'mongodb',
 'node',
 'react',
 'user']

In [15]:
vectors

array([[2, 2, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 2, 0, 0],
       [0, 0, 2, ..., 0, 0, 1],
       ...,
       [2, 0, 0, ..., 0, 3, 0],
       [0, 0, 0, ..., 2, 0, 0],
       [0, 0, 0, ..., 2, 1, 0]], dtype=int64)

In [16]:
similarity = cosine_similarity(vectors)
s = cosine_similarity(vectors, vector)

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 100 while Y.shape[1] == 15

In [17]:
similarity

array([[1.        , 0.29180696, 0.25195163, ..., 0.54605352, 0.04004809,
        0.36985705],
       [0.29180696, 1.        , 0.47380354, ..., 0.26005202, 0.30809364,
        0.6139954 ],
       [0.25195163, 0.47380354, 1.        , ..., 0.14777012, 0.24384603,
        0.47410466],
       ...,
       [0.54605352, 0.26005202, 0.14777012, ..., 1.        , 0.01509961,
        0.2495417 ],
       [0.04004809, 0.30809364, 0.24384603, ..., 0.01509961, 1.        ,
        0.27129471],
       [0.36985705, 0.6139954 , 0.47410466, ..., 0.2495417 , 0.27129471,
        1.        ]])

In [21]:
def recommend(job):
    job_index = jobs[jobs['Job Title'] == job].index[0]
    distances = similarity[job_index]
    jobs_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:100]
    
    for i in jobs_list:
        print(jobs.iloc[i[0]].Jobs)

In [26]:
recommend('iOS Developer')

iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
Flutter Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
Flutter Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
Flutter Developer
iOS Developer
iOS Developer
iOS Developer
Flutter Developer
iOS Developer
Flutter Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
Flutter Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
Flutter Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
Flutter Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
Flutter Developer
iOS Developer
iOS Developer
iOS Developer
iOS Developer
iOS Develope

In [20]:
s = cosine_similarity("sdfgsdfg", "ewdfwsf")

ValueError: could not convert string to float: 'sdfgsdfg'